# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZHDO-nVEET32Wt47_TS8DNzZuTgtKK4K
"""

!pip install sacrebleu

from sacrebleu.metrics import TER

def IzracunajWER(prevod, referenca):
  # Razdelimo referenco in prevod na besede
	besede_referenca = referenca.split()
	besede_prevod = prevod.split()

  # Preštejemo število zamenjav, brisanj in vstavljanj
	Z = sum(1 for r, p in zip(besede_referenca, besede_prevod) if r != p)
	B = len(besede_referenca) - len(besede_prevod)
	V = len(besede_prevod) - len(besede_referenca)

  # Pridobimo skupno število besed v referenčni povedi (N)
	N = len(besede_referenca)

  # Izračunamo oceno WER
	ocena_WER = (Z + B + V) / N

	return ocena_WER

def IzracunajTER(prevod, referenca):
    # Ustvarimo nov objekt TER iz knjižnice sacrebleu
    ter = TER()

    # Izračunamo oceno TER
    ocena_TER = ter.sentence_score(prevod, [referenca])

    return ocena_TER.score/100

referenca = 'danes je lep dan'
prevod = 'lep dan je danes'

wer = IzracunajWER(prevod, referenca)
wer

ter = IzracunajTER(prevod, referenca)
ter