# -*- coding: utf-8 -*-
"""tehnike predobdelave besedil.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YaIV53ZH8n3QQ3uzgWhCZf1noJelY3SJ
"""

#!pip install Lemmagen
#!pip install nltk

from gensim import utils
from pprint import pprint
import nltk
from nltk.corpus import stopwords
import lemmagen.lemmatizer
from lemmagen.lemmatizer import Lemmatizer

"""## 1. Vhodno besedilo """

text = "Popili so bili ravnokar popoldansko kavo: prazne steklenice so bile še na mizi, pogrnjeni z nedeljskim prtom."
print("VHODNO BESEDILO")
pprint(text)
#print("\nsize="+str(len(text)))

"""## 2. Tokenizacija in prečiščevanje"""

tokens = utils.simple_preprocess(text, deacc=False, min_len=3, max_len=15)
pprint(tokens)
#print("\nsize="+str(len(tokens)))

"""## 3. Odstranjevanje blokiranih besed"""

nltk.download('stopwords')
stop = stopwords.words('slovene')

filtered = [word for word in tokens if word not in stop]
pprint(filtered)
#print("\nsize="+str(len(filtered)))

"""## 4. Lematizacija"""

lemmatizer = Lemmatizer(dictionary=lemmagen.DICTIONARY_SLOVENE)
lemmatized = [lemmatizer.lemmatize(word) for word in filtered]
pprint(lemmatized)
#print("\nsize="+str(len(lemmatized)))